### ISSUE TITLE
jdk9 can't run FX2D sketches even with runPropane() fix

### ISSUE THREAD

**Issue by monkstone** [ruby-processing/propane#20]
### Environment
NB: jdk9.0.4 from oracle includes javafx jars.

Using custom propane (compiled with jdk9.0.4 targeting jdk8) modified to use `public runPropane()` instead of `protected runSketch()` test sketch see https://github.com/ruby-processing/propane-examples/blob/master/processing_app/basics/arrays/array_objects.rb. 

### Expected Behavior

Sketch runs fine with open-jdk8 (with javafx), and also with default renderer (and jdk9.0.4).

### Actual Behavior
```bash
Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoSuchMethodError: com.sun.glass.ui.Screen.getRenderScale()F
	at processing.javafx.PSurfaceFX$PApplicationFX.start(PSurfaceFX.java:249)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more
```

**Comment by monkstone** [comment]
Tried to compile processing-core with jdk9 found `PSurfaceFX.java` refers to proprietary code `com.sun.glass.ui.Screen` which is probably why FX2D sketches wont run with jdk9, something for processing.org guys to fix.

**Comment by monkstone** [comment]
Fixed by creating `runPropane` method in processing core source. We now compile propane as a single jar (bar opengl).
